apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analytics-service-secrets
  namespace: user-services
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: analytics-service-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aistartup-dev/db-credentials
        version: "AWSCURRENT"
