apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: user-services
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/aistartup-user-service-irsa
