apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: user-services
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  namespaceSelector:
    matchNames:
      - user-services
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
