import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { generateKeyPairSync, randomUUID } from 'node:crypto'

import chalk from 'chalk'
import { importPKCS8, importSPKI, jwtVerify, SignJWT } from 'jose'
import ora from 'ora'

import { getRepoRoot } from '../lib/repoRoot.js'

const WRITE_FLAG = process.argv.includes('--write')

async function validateKeyPair(privatePem: string, publicPem: string): Promise<void> {
  const privateKey = await importPKCS8(privatePem, 'RS256')
  const publicKey = await importSPKI(publicPem, 'RS256')
  const token = await new SignJWT({ ping: true })
    .setProtectedHeader({ alg: 'RS256' })
    .setSubject('keygen-selftest')
    .setIssuer('ai-startup-builder')
    .setIssuedAt()
    .setExpirationTime('1m')
    .setJti(randomUUID())
    .sign(privateKey)

  await jwtVerify(token, publicKey, { issuer: 'ai-startup-builder', algorithms: ['RS256'] })
}

async function main(): Promise<void> {
  const spinner = ora({ color: 'cyan', text: 'Generating RS256 (2048-bit RSA) key pair…' }).start()

  try {
    const { publicKey, privateKey } = generateKeyPairSync('rsa', {
      modulusLength: 2048,
      publicKeyEncoding: { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    })

    await validateKeyPair(privateKey, publicKey)

    spinner.succeed(chalk.green('Keys generated and verified with jose (sign + verify).'))

    const privB64 = Buffer.from(privateKey, 'utf8').toString('base64')
    const pubB64 = Buffer.from(publicKey, 'utf8').toString('base64')

    const sep = chalk.dim('─'.repeat(72))

    console.log()
    console.log(sep)
    console.log(chalk.bold.cyan('JWT_PRIVATE_KEY_BASE64=') + chalk.white(privB64))
    console.log(chalk.bold.cyan('JWT_PUBLIC_KEY_BASE64=') + chalk.white(pubB64))
    console.log(sep)
    console.log(chalk.yellow('Add these two lines to your ') + chalk.bold('.env.local') + chalk.yellow(' file.'))
    console.log()

    if (WRITE_FLAG) {
      const root = getRepoRoot()
      const outPath = join(root, '.env.keys')
      const content =
        `# Generated by pnpm generate-keys --write (gitignored)\n` +
        `JWT_PRIVATE_KEY_BASE64=${privB64}\n` +
        `JWT_PUBLIC_KEY_BASE64=${pubB64}\n`
      mkdirSync(root, { recursive: true })
      writeFileSync(outPath, content, 'utf8')
      console.log(chalk.green(`✓ Also wrote keys to ${outPath}`))
    }
  } catch (err) {
    spinner.fail(chalk.red('Key generation or validation failed.'))
    console.error(err)
    process.exitCode = 1
  }
}

await main()
