import archiver from 'archiver'
import type { Phase2Output } from '@repo/types'

import * as phaseOutputsQueries from '../db/queries/phaseOutputs.queries.js'
import * as projectFilesQueries from '../db/queries/projectFiles.queries.js'
import * as projectsQueries from '../db/queries/projects.queries.js'

import type { PhaseOutput, Project } from '../db/schema.js'

function zipPathForProjectFile(path: string): string {
  const p = path.replace(/^\/+/, '').replace(/\\/g, '/')
  if (p.startsWith('src/')) return p
  return `src/${p}`
}

export function generateReadme(project: Project, phase2Output?: PhaseOutput): string {
  const d = phase2Output?.outputData as Partial<Phase2Output> | undefined
  const frontendStack = d?.frontendStack ?? 'Not specified'
  const backendStack = d?.backendStack ?? 'Not specified'
  const dbChoice = d?.dbChoice ?? 'Not specified'

  const progress = project.phaseProgress as Record<string, string>
  const phaseLines = [1, 2, 3, 4, 5, 6].map((phase) => {
    const st = progress[String(phase)] ?? 'unknown'
    return `- Phase ${phase}: ${st}`
  })

  return `# ${project.name}

Generated by AI Startup Builder

## Tech Stack
- Frontend: ${frontendStack}
- Backend: ${backendStack}
- Database: ${dbChoice}

## Phases Completed
${phaseLines.join('\n')}

## Getting Started
1. Install dependencies for the frontend (${frontendStack}) and backend (${backendStack}) stacks described above.
2. Configure environment variables and ${dbChoice} connection strings as needed.
3. Open exported files under \`src/\` and phase JSON under \`phase-outputs/\` for full context.
`
}

export async function generateZip(projectId: string, includePhases: number[]): Promise<Buffer> {
  const project = await projectsQueries.findProjectById(projectId)
  if (!project) throw new Error('Project not found')

  const allOutputs = await phaseOutputsQueries.findAllPhaseOutputs(projectId)
  const outputs = allOutputs.filter((o) => includePhases.includes(o.phase))
  const files = await projectFilesQueries.findFilesByProject(projectId)
  const phase2 = outputs.find((o) => o.phase === 2)

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    const archive = archiver('zip', { zlib: { level: 9 } })
    archive.on('data', (chunk: Buffer) => chunks.push(chunk))
    archive.on('error', reject)
    archive.on('end', () => resolve(Buffer.concat(chunks)))

    const info = {
      name: project.name,
      emoji: project.emoji,
      currentPhase: project.currentPhase,
      createdAt:
        project.createdAt instanceof Date ? project.createdAt.toISOString() : project.createdAt,
    }
    archive.append(JSON.stringify(info, null, 2), { name: 'project-info.json' })

    for (const o of outputs) {
      archive.append(JSON.stringify(o.outputData, null, 2), {
        name: `phase-outputs/phase-${o.phase}.json`,
      })
    }

    for (const f of files) {
      archive.append(f.content, { name: zipPathForProjectFile(f.path) })
    }

    archive.append(generateReadme(project, phase2), { name: 'README.md' })

    void archive.finalize()
  })
}
