import archiver from 'archiver'
import { PassThrough } from 'node:stream'
import { finished } from 'node:stream/promises'

import * as phaseOutputsQueries from '../db/queries/phaseOutputs.queries.js'
import * as projectFilesQueries from '../db/queries/projectFiles.queries.js'
import * as projectsQueries from '../db/queries/projects.queries.js'

import type { PhaseOutput, Project } from '../db/schema.js'

function pickStack(data: Record<string, unknown>, keys: string[]): string {
  for (const k of keys) {
    const v = data[k]
    if (typeof v === 'string' && v.trim()) return v.trim()
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      const s = JSON.stringify(v)
      if (s.length < 500) return s
    }
  }
  return 'Not specified'
}

export function generateReadme(project: Project, phase2Output?: PhaseOutput): string {
  const od = (phase2Output?.outputData ?? {}) as Record<string, unknown>
  const frontend = pickStack(od, [
    'frontendStack',
    'frontend',
    'frontend_stack',
    'clientStack',
  ])
  const backend = pickStack(od, ['backendStack', 'backend', 'backend_stack', 'serverStack'])
  const database = pickStack(od, ['database', 'dbChoice', 'db', 'databaseChoice'])

  const progress = (project.phaseProgress ?? {}) as Record<string, string>
  const phaseLines: string[] = []
  for (let p = 1; p <= 6; p++) {
    const st = progress[String(p)] ?? 'unknown'
    phaseLines.push(`- Phase ${p}: ${st}`)
  }

  let gettingStarted =
    '1. Install dependencies for your frontend and backend as described in phase outputs.\n' +
    '2. Configure environment variables for API URLs and database connection.\n' +
    '3. Run development servers and open the app in your browser.'

  if (frontend !== 'Not specified' && backend !== 'Not specified') {
    gettingStarted =
      `This project targets **${frontend}** on the client and **${backend}** on the server. ` +
      `Follow the setup commands from your Phase 4 generated files under \`src/\`.`
  }

  return [
    `# ${project.name} ${project.emoji}`,
    '',
    'Generated by AI Startup Builder',
    '',
    '## Tech Stack',
    '',
    `- Frontend: ${frontend}`,
    `- Backend: ${backend}`,
    `- Database: ${database}`,
    '',
    '## Phases Completed',
    '',
    ...phaseLines,
    '',
    '## Getting Started',
    '',
    gettingStarted,
    '',
  ].join('\n')
}

export async function generateZip(projectId: string, includePhases: number[]): Promise<Buffer> {
  const project = await projectsQueries.findProjectById(projectId)
  if (!project) {
    throw new Error('Project not found')
  }

  const allOutputs = await phaseOutputsQueries.findAllPhaseOutputs(projectId)
  const outputs = allOutputs.filter((o) => includePhases.includes(o.phase))
  const phase2 = outputs.find((o) => o.phase === 2)
  const files = await projectFilesQueries.findFilesByProject(projectId)

  const archive = archiver('zip', { zlib: { level: 9 } })
  const pass = new PassThrough()
  const chunks: Buffer[] = []
  pass.on('data', (c: Buffer) => chunks.push(c))

  archive.pipe(pass)

  const projectInfo = {
    name: project.name,
    emoji: project.emoji,
    currentPhase: project.currentPhase,
    createdAt: project.createdAt instanceof Date ? project.createdAt.toISOString() : project.createdAt,
  }
  archive.append(JSON.stringify(projectInfo, null, 2), { name: 'project-info.json' })

  for (const out of outputs) {
    archive.append(JSON.stringify(out.outputData, null, 2), {
      name: `phase-outputs/phase-${out.phase}.json`,
    })
  }

  for (const f of files) {
    const name = f.path.replace(/^\/+/, '')
    archive.append(f.content, { name: name.startsWith('src/') ? name : `src/${name}` })
  }

  archive.append(generateReadme(project, phase2), { name: 'README.md' })

  const done = finished(pass)
  await archive.finalize()
  await done

  return Buffer.concat(chunks)
}
